import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1>Welcome to tailwind css - Hulu</h1> */}
      {/* header */}
      <Header />

      {/* nav */}

      {/* results */}
    </div>
  )
}
